/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.uas.oop.view.component;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itenas.uas.oop.pojo.Admin;
import org.itenas.uas.oop.pojo.Buku;
import org.itenas.uas.oop.pojo.Komik;
import org.itenas.uas.oop.pojo.Member;
import org.itenas.uas.oop.pojo.Sewa;
import org.itenas.uas.oop.pojo.Transaksi;
import org.itenas.uas.oop.service.SewaService;
import org.itenas.uas.oop.service.TransaksiService;
import org.itenas.uas.oop.serviceimpl.MemberServiceImpl;
import org.itenas.uas.oop.serviceimpl.SewaServiceImpl;
import org.itenas.uas.oop.serviceimpl.TransaksiServiceImpl;
import static org.itenas.uas.oop.view.component.SewaBuku.listSewa;
import org.itenas.uas.oop.view.main.Main;

/**
 *
 * @author Andre
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    SewaService sewaService;
    Admin admin;
    Transaksi transaksi;
    TransaksiService transaksiService;
    
    public AdminDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        table_transaksi.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table_transaksi.getModel();
        loadData();
    }
    
    public void loadData() {
        sewaService = new SewaServiceImpl();
        transaksi = new Transaksi();
        transaksiService = new TransaksiServiceImpl();
        transaksi = transaksiService.statusAdmin();
        
        int totalPenyewaan;
        double totalPendapatan;
        totalPendapatan = transaksi.getTotalHarga();
        totalPenyewaan = transaksi.getJumlah();
        
        List<Sewa> listSewa = sewaService.findAll(); 
         Object[][] objectSewa = new Object[listSewa.size()][9];
        
        int counter = 0;

        for (Sewa sewa : listSewa) {
            objectSewa[counter][0] = sewa.getId();
            objectSewa[counter][1] = sewa.getTglSewa();
            objectSewa[counter][2] = sewa.getTglKembali();
            objectSewa[counter][3] = sewa.getTotalHarga();
            objectSewa[counter][4] = sewa.getDenda();
            objectSewa[counter][5] = sewa.getStatus();
            objectSewa[counter][6] = sewa.getBuku().getId();
            objectSewa[counter][7] = sewa.getKomik().getId();
            objectSewa[counter][8] = sewa.getMember().getId();
            counter++;
        }                                         
        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
                objectSewa,
                new String[]{
                        "ID Sewa", "Tgl Sewa", "Tgl Kembali", "Total Harga", "Denda", "Status", "ID Buku", "ID Komik", "ID Member"
                        
                }
        ));
        
        lbl_totalPendapatan.setText("Rp."+totalPendapatan);
        lbl_totalPenyewaan.setText(totalPenyewaan+"");
    
    }

    public Admin getInfo(Admin adm){
        admin = adm;
        lbl_namaAdmin.setText(admin.getAkun().getUsername());
        
        return admin;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sewaBuku = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        sewaBuku1 = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        sewaBuku2 = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        sewaBuku4 = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        btn_pengembalian = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        btn_transaksi1 = new org.itenas.uas.oop.view.component.swing.ButtonOutLine();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_totalPendapatan = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_totalPenyewaan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transaksi = new org.itenas.uas.oop.view.component.swing.TableDark();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_namaAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 55, 55));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        sewaBuku.setForeground(new java.awt.Color(255, 255, 255));
        sewaBuku.setText("Manage Buku");
        sewaBuku.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sewaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaBukuActionPerformed(evt);
            }
        });

        sewaBuku1.setForeground(new java.awt.Color(255, 255, 255));
        sewaBuku1.setText("Manage Komik");
        sewaBuku1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sewaBuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaBuku1ActionPerformed(evt);
            }
        });

        sewaBuku2.setForeground(new java.awt.Color(255, 255, 255));
        sewaBuku2.setText("Manage Member");
        sewaBuku2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sewaBuku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaBuku2ActionPerformed(evt);
            }
        });

        sewaBuku4.setForeground(new java.awt.Color(255, 255, 255));
        sewaBuku4.setText("Logout");
        sewaBuku4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sewaBuku4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaBuku4ActionPerformed(evt);
            }
        });

        btn_pengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengembalian.setText("Pengembalian");
        btn_pengembalian.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengembalianActionPerformed(evt);
            }
        });

        btn_transaksi1.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi1.setText("Konfirmasi Transaksi");
        btn_transaksi1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_transaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sewaBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sewaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sewaBuku2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sewaBuku4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(597, 597, 597)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sewaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(sewaBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(sewaBuku2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btn_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(sewaBuku4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(187, 187, 187));

        jPanel7.setBackground(new java.awt.Color(245, 172, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Pendapatan");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lbl_totalPendapatan.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_totalPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalPendapatan.setText("Rp. ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_totalPendapatan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lbl_totalPendapatan)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 170));

        jPanel6.setBackground(new java.awt.Color(187, 187, 187));

        jPanel8.setBackground(new java.awt.Color(245, 172, 44));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Penyewaan");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lbl_totalPenyewaan.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        lbl_totalPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalPenyewaan.setText("-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbl_totalPenyewaan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbl_totalPenyewaan)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 250, 170));

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Sewa", "Tgl Sewa", "Tgl Kembali", "Total Harga", "Denda", "Status", "ID Buku", "ID Komik", "ID Member"
            }
        ));
        table_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_transaksi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 810, 280));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 172, 44));
        jLabel6.setText("Daftar Penyewaan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 830, 620));

        jPanel5.setBackground(new java.awt.Color(245, 172, 44));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome,");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 37));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logopitimoss.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -30, -1, -1));

        lbl_namaAdmin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbl_namaAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_namaAdmin.setText("Nama Admin");
        jPanel5.add(lbl_namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 29, -1, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_transaksiMouseClicked
        
    }//GEN-LAST:event_table_transaksiMouseClicked

    private void sewaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaBukuActionPerformed
       BukuManagement BukuManajemen = new BukuManagement();
       BukuManajemen.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_sewaBukuActionPerformed

    private void sewaBuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaBuku1ActionPerformed
        KomikManagement komikManajemen = new KomikManagement();
       komikManajemen.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_sewaBuku1ActionPerformed

    private void sewaBuku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaBuku2ActionPerformed
        MemberManagement memberManajemen = new MemberManagement();
       memberManajemen.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_sewaBuku2ActionPerformed

    private void sewaBuku4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaBuku4ActionPerformed
         int dialogButton = JOptionPane.YES_NO_OPTION;
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah anda yakin ingin logout", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            Main login = new Main();
       login.setVisible(true);
       this.dispose();

        }
    }//GEN-LAST:event_sewaBuku4ActionPerformed

    private void btn_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengembalianActionPerformed
        FormPengembalian formPengembalian = new FormPengembalian();
        formPengembalian.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_pengembalianActionPerformed

    private void btn_transaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi1ActionPerformed
        FormTransaksiAdmin formTransaksi = new FormTransaksiAdmin();
        formTransaksi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine btn_pengembalian;
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine btn_transaksi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_namaAdmin;
    private javax.swing.JLabel lbl_totalPendapatan;
    private javax.swing.JLabel lbl_totalPenyewaan;
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine sewaBuku;
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine sewaBuku1;
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine sewaBuku2;
    private org.itenas.uas.oop.view.component.swing.ButtonOutLine sewaBuku4;
    private org.itenas.uas.oop.view.component.swing.TableDark table_transaksi;
    // End of variables declaration//GEN-END:variables
}
