/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.uas.view.component;

import org.itenas.uas.pojo.Buku;
import org.itenas.uas.service.BukuService;
import org.itenas.uas.serviceimpl.BukuServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author BillHafidz
 */
public class BukuManagement extends javax.swing.JFrame {

    /**
     * Creates new form Tes
     */
    
    BukuService bukuService;
    
    public BukuManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txt_id_buku.setText("");
        txt_judul.setText("");
        txt_pengarang.setText("");
        txt_penerbit.setText("");
        txt_tahunTerbit.setText("");
        txt_harga.setText("");
        group_stat.clearSelection();
    }
    
    private void loadData() {
        bukuService = new BukuServiceImpl();
        List<Buku> listBuku = new ArrayList<>();
        listBuku = bukuService.findAll();
        Object[][] objectBuku = new Object[listBuku.size()][7];
        
        int counter = 0;
        
        for (Buku buku : listBuku) {
            objectBuku[counter][0] = buku.getId();
            objectBuku[counter][1] = buku.getJudul();
            objectBuku[counter][2] = buku.getPengarang();
            objectBuku[counter][3] = buku.getPenerbit();
            objectBuku[counter][4] = buku.getTahunTerbit();
            objectBuku[counter][5] = buku.getHarga();
            objectBuku[counter][6] = buku.getStatus();
            counter++;
        }
        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            objectBuku,
            new String [] {
                "ID Buku", "Judul Buku", "Pengarang", "Penerbit", "Tahun Terbit", "Harga Buku", "Status"
            }
        ));
    }
    
    private void loadData(Buku buku) {
        Object[][] objectBuku = new Object[1][7];
        
        objectBuku[0][0] = buku.getId();
        objectBuku[0][1] = buku.getJudul();
        objectBuku[0][2] = buku.getPengarang();
        objectBuku[0][3] = buku.getPenerbit();
        objectBuku[0][4] = buku.getTahunTerbit();
        objectBuku[0][5] = buku.getHarga();
        objectBuku[0][6] = buku.getStatus();
            
        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            objectBuku,
            new String [] {
                "ID Buku", "Judul", "Pengarang", "Penerbit", "Tahun Terbit", "Harga", "Status"
            }
        ));
    }
    
    private Buku findBuku(String id) {
        Buku buku = new Buku();
        bukuService = new BukuServiceImpl();
        buku = bukuService.findById(id);
    
        return buku;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_stat = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_print = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        txt_search_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_buku = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        radio_tersedia = new javax.swing.JRadioButton();
        radio_tidak_tersedia = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_tahunTerbit = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        admin_dashboard_item = new javax.swing.JMenuItem();
        komik_management_item = new javax.swing.JMenuItem();
        member_management_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 800));

        jPanel1.setBackground(new java.awt.Color(245, 172, 44));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_print.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_print.setText("PRINT");
        btn_print.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_refresh.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        txt_search_id.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        txt_search_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_idMouseClicked(evt);
            }
        });
        txt_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_idActionPerformed(evt);
            }
        });
        txt_search_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_search_idKeyTyped(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUKU MANAGEMENT");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-books-100.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_search_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh))
                .addGap(505, 505, 505)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        txt_id_buku.setBackground(new java.awt.Color(245, 172, 45));
        txt_id_buku.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_id_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_bukuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Buku");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul BUku");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_judul.setBackground(new java.awt.Color(245, 172, 44));
        txt_judul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_judul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_judulActionPerformed(evt);
            }
        });

        group_stat.add(radio_tersedia);
        radio_tersedia.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        radio_tersedia.setForeground(new java.awt.Color(255, 255, 255));
        radio_tersedia.setText("Tersedia");
        radio_tersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_tersediaActionPerformed(evt);
            }
        });

        group_stat.add(radio_tidak_tersedia);
        radio_tidak_tersedia.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        radio_tidak_tersedia.setForeground(new java.awt.Color(255, 255, 255));
        radio_tidak_tersedia.setText("Tidak Tersedia");
        radio_tidak_tersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_tidak_tersediaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pengarang");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Penerbit");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tahun Terbit");

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status");

        txt_tahunTerbit.setBackground(new java.awt.Color(245, 172, 44));
        txt_tahunTerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tahunTerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_tahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tahunTerbitActionPerformed(evt);
            }
        });

        txt_pengarang.setBackground(new java.awt.Color(245, 172, 44));
        txt_pengarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pengarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pengarangActionPerformed(evt);
            }
        });

        txt_harga.setBackground(new java.awt.Color(245, 172, 44));
        txt_harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        txt_penerbit.setBackground(new java.awt.Color(245, 172, 44));
        txt_penerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_penerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_penerbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(txt_pengarang)
                    .addComponent(txt_judul)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_penerbit)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_tidak_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(632, 632, 632))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radio_tersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radio_tidak_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        admin_dashboard_item.setText("Admin Dashboard");
        admin_dashboard_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_dashboard_itemActionPerformed(evt);
            }
        });
        jMenu1.add(admin_dashboard_item);

        komik_management_item.setText("Komik Management");
        komik_management_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komik_management_itemActionPerformed(evt);
            }
        });
        jMenu1.add(komik_management_item);

        member_management_item.setText("Member Management");
        member_management_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_management_itemActionPerformed(evt);
            }
        });
        jMenu1.add(member_management_item);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_judulActionPerformed

    private void txt_tahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahunTerbitActionPerformed

    private void txt_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pengarangActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void radio_tersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_tersediaActionPerformed
        stat = "Tersedia";
    }//GEN-LAST:event_radio_tersediaActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String id_buku, judul, pengarang, penerbit, tahunTerbit, status;
        double harga;
        bukuService = new BukuServiceImpl();
        
        id_buku = txt_id_buku.getText();
        judul = txt_judul.getText();
        pengarang = txt_pengarang.getText();
        penerbit = txt_penerbit.getText();
        tahunTerbit = txt_tahunTerbit.getText();  
        harga = Double.parseDouble(txt_harga.getText());
        status = stat;
        
        Buku buku = new Buku();
        buku.setId(id_buku);
        buku.setJudul(judul);
        buku.setPengarang(pengarang);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(tahunTerbit);
        buku.setHarga(harga);
        buku.setStatus(status);
        
        bukuService.create(buku);
        JOptionPane.showMessageDialog(null, "Data buku berhasil dibuat!");
        loadData();
        emptyField();
    }//GEN-LAST:event_btn_addActionPerformed

    private void radio_tidak_tersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_tidak_tersediaActionPerformed
        stat = "Tidak Tersedia";
    }//GEN-LAST:event_radio_tidak_tersediaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String id_buku, judul, pengarang, penerbit, tahunTerbit, status;
        double harga;
        bukuService = new BukuServiceImpl();
        
        id_buku = txt_id_buku.getText();
        judul = txt_judul.getText();
        pengarang = txt_pengarang.getText();
        penerbit = txt_penerbit.getText();
        tahunTerbit = txt_tahunTerbit.getText();
        harga = Double.parseDouble(txt_harga.getText());
        status = stat;

        
        Buku buku = new Buku();
        buku.setId(id_buku);
        buku.setJudul(judul);
        buku.setPengarang(pengarang);
        buku.setPenerbit(penerbit);
        buku.setTahunTerbit(tahunTerbit);
        buku.setHarga(harga);
        buku.setStatus(status);

        bukuService.update(buku);
        JOptionPane.showMessageDialog(null, "Data buku berhasil di update!");
        loadData();
        emptyField(); 
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String id_buku;
        bukuService = new BukuServiceImpl();
        int dialogButton = JOptionPane.YES_NO_OPTION;
        
        id_buku = txt_id_buku.getText();
        
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah anda yakin untuk menghapus?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            bukuService.delete(id_buku);
            JOptionPane.showMessageDialog(null, "Data buku berhasil di hapus!");
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void admin_dashboard_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_dashboard_itemActionPerformed

    }//GEN-LAST:event_admin_dashboard_itemActionPerformed

    private void komik_management_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komik_management_itemActionPerformed
        KomikManagement komikManagement = new KomikManagement();
        komikManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_komik_management_itemActionPerformed

    private void txt_id_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_bukuActionPerformed

    private void txt_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_penerbitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        emptyField();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String id_buku;
        Buku searchedBuku = new Buku();

        id_buku = txt_search_id.getText();
        searchedBuku = findBuku(id_buku);
        if (searchedBuku != null) {
            loadData(searchedBuku);
        } else {
            JOptionPane.showMessageDialog(null, "Data dengan id '" + id_buku + "'tidak ditemukan!");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_search_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyTyped

    }//GEN-LAST:event_txt_search_idKeyTyped

    private void txt_search_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyReleased
        DefaultTableModel ob = (DefaultTableModel)tabel_buku.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tabel_buku.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter("(?i)"+txt_search_id.getText()));
    }//GEN-LAST:event_txt_search_idKeyReleased

    private void txt_search_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyPressed

    }//GEN-LAST:event_txt_search_idKeyPressed

    private void txt_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_idActionPerformed
        txt_search_id.setText("");
    }//GEN-LAST:event_txt_search_idActionPerformed

    private void txt_search_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_idMouseClicked
        txt_search_id.setText("");
    }//GEN-LAST:event_txt_search_idMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        loadData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        MessageFormat header = new MessageFormat("Laporan List Buku");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            tabel_buku.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void tabel_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bukuMouseClicked
        String id_buku, judul, pengarang, penerbit, tahunTerbit, status;
        double harga;

        int row = tabel_buku.getSelectedRow();
        id_buku = tabel_buku.getValueAt(row, 0).toString();
        judul = tabel_buku.getValueAt(row, 1).toString();
        pengarang = tabel_buku.getValueAt(row, 2).toString();
        penerbit = tabel_buku.getValueAt(row, 3).toString();
        tahunTerbit = tabel_buku.getValueAt(row, 4).toString();
        harga = Double.parseDouble(tabel_buku.getValueAt(row, 5).toString());
        status = tabel_buku.getValueAt(row, 6).toString();

        txt_id_buku.setText(id_buku);
        txt_judul.setText(judul);
        txt_pengarang.setText(pengarang);
        txt_penerbit.setText(penerbit);
        txt_tahunTerbit.setText(tahunTerbit);
        txt_harga.setText(harga+"");
        
        if (status.equals("Tersedia")) {
            radio_tersedia.setSelected(true);
        }
        if (status.equals("Tidak Tersedia")) {
            radio_tidak_tersedia.setSelected(true);
        }
    }//GEN-LAST:event_tabel_bukuMouseClicked

    private void member_management_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_management_itemActionPerformed
        MemberManagement memberManagement = new MemberManagement();
        memberManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_member_management_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin_dashboard_item;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private javax.swing.ButtonGroup group_stat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem komik_management_item;
    private javax.swing.JMenuItem member_management_item;
    private javax.swing.JRadioButton radio_tersedia;
    private javax.swing.JRadioButton radio_tidak_tersedia;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id_buku;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_search_id;
    private javax.swing.JTextField txt_tahunTerbit;
    // End of variables declaration//GEN-END:variables
    private String stat;
}
