/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.uas.view.component;

import org.itenas.uas.pojo.Komik;
import org.itenas.uas.service.KomikService;
import org.itenas.uas.serviceimpl.KomikServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author BillHafidz
 */
public class KomikManagement extends javax.swing.JFrame {

    /**
     * Creates new form PanelKomik
     */
    
    KomikService komikService;
    
    public KomikManagement() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    private void emptyField() {
        txt_id_komik.setText("");
        txt_judul.setText("");
        txt_pengarang.setText("");
        txt_penerbit.setText("");
        txt_tahunTerbit.setText("");
        txt_harga.setText("");
        group_stat.clearSelection();
        txt_volume.setText("");
    }
    
    private void loadData() {
        komikService = new KomikServiceImpl();
        List<Komik> listKomik = new ArrayList<>();
        listKomik = komikService.findAll();
        Object[][] objectKomik = new Object[listKomik.size()][8];
        
        int counter = 0;
        
        for (Komik komik : listKomik) {
            objectKomik[counter][0] = komik.getId();
            objectKomik[counter][1] = komik.getJudul();
            objectKomik[counter][2] = komik.getPengarang();
            objectKomik[counter][3] = komik.getPenerbit();
            objectKomik[counter][4] = komik.getTahunTerbit();
            objectKomik[counter][5] = komik.getHarga();
            objectKomik[counter][6] = komik.getStatus();
            objectKomik[counter][7] = komik.getVolume();
            counter++;
        }
        tabel_komik.setModel(new javax.swing.table.DefaultTableModel(
            objectKomik,
            new String [] {
                "ID Komik", "Judul Komik", "Pengarang", "Penerbit", "Tahun Terbit", "Harga Komik", "Status", "Volume"
            }
        ));
    }
    
    private void loadData(Komik komik) {
        Object[][] objectKomik = new Object[1][8];
        
        objectKomik[0][0] = komik.getId();
        objectKomik[0][1] = komik.getJudul();
        objectKomik[0][2] = komik.getPengarang();
        objectKomik[0][3] = komik.getPenerbit();
        objectKomik[0][4] = komik.getTahunTerbit();
        objectKomik[0][5] = komik.getHarga();
        objectKomik[0][6] = komik.getStatus();
        objectKomik[0][7] = komik.getVolume();
            
        tabel_komik.setModel(new javax.swing.table.DefaultTableModel(
            objectKomik,
            new String [] {
                "ID Komik", "Judul", "Pengarang", "Penerbit", "Tahun Terbit", "Harga", "Status", "Volume"
            }
        ));
    }
    
    private Komik findKomik(String id) {
        Komik komik = new Komik();
        komikService = new KomikServiceImpl();
        komik = komikService.findById(id);
    
        return komik;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_stat = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_komik = new org.itenas.uas.view.component.swing.TableDark();
        btn_print = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        txt_search_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        txt_id_komik = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        radio_tersedia = new javax.swing.JRadioButton();
        radio_tidak_tersedia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_clear = new org.itenas.uas.view.component.swing.Button();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_tahunTerbit = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        btn_add = new org.itenas.uas.view.component.swing.Button();
        btn_update = new org.itenas.uas.view.component.swing.Button();
        btn_delete = new org.itenas.uas.view.component.swing.Button();
        txt_penerbit = new javax.swing.JTextField();
        txt_volume = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin_dashboard_item = new javax.swing.JMenu();
        admin_dashboard_item2 = new javax.swing.JMenuItem();
        buku_management_item = new javax.swing.JMenuItem();
        member_management_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 800));

        jPanel2.setBackground(new java.awt.Color(245, 172, 44));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KOMIK MANAGEMENT");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/komik.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        tabel_komik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Komik", "Judul Komik", "Pengarang", "Penerbit", "Tahun Terbit", "Harga", "Status", "Volume"
            }
        ));
        tabel_komik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_komikMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_komik);

        btn_print.setBackground(new java.awt.Color(255, 255, 255));
        btn_print.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_print.setForeground(new java.awt.Color(0, 0, 0));
        btn_print.setText("PRINT");
        btn_print.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(255, 255, 255));
        btn_refresh.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(0, 0, 0));
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        txt_search_id.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        txt_search_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_idMouseClicked(evt);
            }
        });
        txt_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_idActionPerformed(evt);
            }
        });
        txt_search_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_search_idKeyTyped(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(255, 255, 255));
        btn_search.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 0, 0));
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_search_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_refresh))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        txt_id_komik.setBackground(new java.awt.Color(245, 172, 45));
        txt_id_komik.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_id_komik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_komikActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID KOMIK");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul Komik");

        txt_judul.setBackground(new java.awt.Color(245, 172, 44));
        txt_judul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_judul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_judulActionPerformed(evt);
            }
        });

        group_stat.add(radio_tersedia);
        radio_tersedia.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        radio_tersedia.setForeground(new java.awt.Color(255, 255, 255));
        radio_tersedia.setText("Tersedia");
        radio_tersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_tersediaActionPerformed(evt);
            }
        });

        group_stat.add(radio_tidak_tersedia);
        radio_tidak_tersedia.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        radio_tidak_tersedia.setForeground(new java.awt.Color(255, 255, 255));
        radio_tidak_tersedia.setText("Tidak Tersedia");
        radio_tidak_tersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_tidak_tersediaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pengarang");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Penerbit");

        btn_clear.setBackground(new java.awt.Color(51, 51, 255));
        btn_clear.setText("CLEAR");
        btn_clear.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tahun Terbit");

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status");

        txt_tahunTerbit.setBackground(new java.awt.Color(245, 172, 44));
        txt_tahunTerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tahunTerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_tahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tahunTerbitActionPerformed(evt);
            }
        });

        txt_pengarang.setBackground(new java.awt.Color(245, 172, 44));
        txt_pengarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_pengarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pengarangActionPerformed(evt);
            }
        });

        txt_harga.setBackground(new java.awt.Color(245, 172, 44));
        txt_harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(51, 204, 0));
        btn_add.setText("ADD");
        btn_add.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 255, 0));
        btn_update.setText("UPDATE");
        btn_update.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setText("DELETE");
        btn_delete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_penerbit.setBackground(new java.awt.Color(245, 172, 44));
        txt_penerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_penerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_penerbitActionPerformed(evt);
            }
        });

        txt_volume.setBackground(new java.awt.Color(245, 172, 44));
        txt_volume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_volume.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_volumeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VOLume");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(txt_pengarang)
                        .addComponent(txt_judul)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_penerbit)
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(radio_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(radio_tidak_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id_komik, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_komik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radio_tersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_tidak_tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        admin_dashboard_item.setText("Menu");
        admin_dashboard_item.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        admin_dashboard_item2.setText("Admin Dashboard");
        admin_dashboard_item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_dashboard_item2ActionPerformed(evt);
            }
        });
        admin_dashboard_item.add(admin_dashboard_item2);

        buku_management_item.setText("Buku Management");
        buku_management_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku_management_itemActionPerformed(evt);
            }
        });
        admin_dashboard_item.add(buku_management_item);

        member_management_item.setText("Member Management");
        member_management_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_management_itemActionPerformed(evt);
            }
        });
        admin_dashboard_item.add(member_management_item);

        jMenuBar1.add(admin_dashboard_item);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_penerbitActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String id_komik;
        komikService = new KomikServiceImpl();
        int dialogButton = JOptionPane.YES_NO_OPTION;

        id_komik = txt_id_komik.getText();

        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah anda yakin untuk menghapus?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            komikService.delete(id_komik);
            JOptionPane.showMessageDialog(null, "Data komik berhasil di hapus!");
            loadData();
            emptyField();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String id_komik, judul, pengarang, penerbit, tahunTerbit, status, volume;
        double harga;
        komikService = new KomikServiceImpl();

        id_komik = txt_id_komik.getText();
        judul = txt_judul.getText();
        pengarang = txt_pengarang.getText();
        penerbit = txt_penerbit.getText();
        tahunTerbit = txt_tahunTerbit.getText();
        harga = Double.parseDouble(txt_harga.getText());
        status = stat;
        volume = txt_volume.getText();

        Komik komik = new Komik();
        komik.setId(id_komik);
        komik.setJudul(judul);
        komik.setPengarang(pengarang);
        komik.setPenerbit(penerbit);
        komik.setTahunTerbit(tahunTerbit);
        komik.setHarga(harga);
        komik.setStatus(status);
        komik.setVolume(volume);

        komikService.update(komik);
        JOptionPane.showMessageDialog(null, "Data komik berhasil di update!");
        loadData();
        emptyField();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String id_komik, judul, pengarang, penerbit, tahunTerbit, status, volume;
        double harga;
        komikService = new KomikServiceImpl();

        id_komik = txt_id_komik.getText();
        judul = txt_judul.getText();
        pengarang = txt_pengarang.getText();
        penerbit = txt_penerbit.getText();
        tahunTerbit = txt_tahunTerbit.getText();
        harga = Double.parseDouble(txt_harga.getText());
        status = stat;
        volume = txt_volume.getText();

        Komik komik = new Komik();
        komik.setId(id_komik);
        komik.setJudul(judul);
        komik.setPengarang(pengarang);
        komik.setPenerbit(penerbit);
        komik.setTahunTerbit(tahunTerbit);
        komik.setHarga(harga);
        komik.setStatus(status);
        komik.setVolume(volume);

        komikService.create(komik);
        JOptionPane.showMessageDialog(null, "Data komik berhasil dibuat!");
        loadData();
        emptyField();
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pengarangActionPerformed

    private void txt_tahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahunTerbitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        emptyField();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void radio_tidak_tersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_tidak_tersediaActionPerformed
        stat = "Tidak Tersedia";
    }//GEN-LAST:event_radio_tidak_tersediaActionPerformed

    private void radio_tersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_tersediaActionPerformed
        stat = "Tersedia";
    }//GEN-LAST:event_radio_tersediaActionPerformed

    private void txt_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_judulActionPerformed

    private void txt_id_komikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_komikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_komikActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String id_komik;
        Komik searchedKomik = new Komik();

        id_komik = txt_search_id.getText();
        searchedKomik = findKomik(id_komik);
        if (searchedKomik != null) {
            loadData(searchedKomik);
        } else {
            JOptionPane.showMessageDialog(null, "Data dengan id '" + id_komik + "'tidak ditemukan!");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_search_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyTyped

    }//GEN-LAST:event_txt_search_idKeyTyped

    private void txt_search_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyReleased
        DefaultTableModel ob = (DefaultTableModel)tabel_komik.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tabel_komik.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter("(?i)"+txt_search_id.getText()));
    }//GEN-LAST:event_txt_search_idKeyReleased

    private void txt_search_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_idKeyPressed

    }//GEN-LAST:event_txt_search_idKeyPressed

    private void txt_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_idActionPerformed
        txt_search_id.setText("");
    }//GEN-LAST:event_txt_search_idActionPerformed

    private void txt_search_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_idMouseClicked
        txt_search_id.setText("");
    }//GEN-LAST:event_txt_search_idMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        loadData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        MessageFormat header = new MessageFormat("Laporan List Komik");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            tabel_komik.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void tabel_komikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_komikMouseClicked
        String id_komik, judul, pengarang, penerbit, tahunTerbit, status, volume;
        double harga;

        int row = tabel_komik.getSelectedRow();
        id_komik = tabel_komik.getValueAt(row, 0).toString();
        judul = tabel_komik.getValueAt(row, 1).toString();
        pengarang = tabel_komik.getValueAt(row, 2).toString();
        penerbit = tabel_komik.getValueAt(row, 3).toString();
        tahunTerbit = tabel_komik.getValueAt(row, 4).toString();
        harga = Double.parseDouble(tabel_komik.getValueAt(row, 5).toString());
        status = tabel_komik.getValueAt(row, 6).toString();
        volume = tabel_komik.getValueAt(row, 7).toString();

        txt_id_komik.setText(id_komik);
        txt_judul.setText(judul);
        txt_pengarang.setText(pengarang);
        txt_penerbit.setText(penerbit);
        txt_tahunTerbit.setText(tahunTerbit);
        txt_harga.setText(harga+"");
        
        if (status.equals("Tersedia")) {
            radio_tersedia.setSelected(true);
        }
        if (status.equals("Tidak Tersedia")) {
            radio_tidak_tersedia.setSelected(true);
        }
        
        txt_volume.setText(volume);
    }//GEN-LAST:event_tabel_komikMouseClicked

    private void txt_volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_volumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_volumeActionPerformed

    private void admin_dashboard_item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_dashboard_item2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_dashboard_item2ActionPerformed

    private void buku_management_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku_management_itemActionPerformed
        BukuManagement bukuManagement = new BukuManagement();
        bukuManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buku_management_itemActionPerformed

    private void member_management_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_management_itemActionPerformed
        MemberManagement memberManagement = new MemberManagement();
        memberManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_member_management_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KomikManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KomikManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KomikManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KomikManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KomikManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu admin_dashboard_item;
    private javax.swing.JMenuItem admin_dashboard_item2;
    private org.itenas.uas.view.component.swing.Button btn_add;
    private org.itenas.uas.view.component.swing.Button btn_clear;
    private org.itenas.uas.view.component.swing.Button btn_delete;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private org.itenas.uas.view.component.swing.Button btn_update;
    private javax.swing.JMenuItem buku_management_item;
    private javax.swing.ButtonGroup group_stat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem member_management_item;
    private javax.swing.JRadioButton radio_tersedia;
    private javax.swing.JRadioButton radio_tidak_tersedia;
    private org.itenas.uas.view.component.swing.TableDark tabel_komik;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id_komik;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_search_id;
    private javax.swing.JTextField txt_tahunTerbit;
    private javax.swing.JTextField txt_volume;
    // End of variables declaration//GEN-END:variables
    private String stat;
}

