/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.uas.view.component;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.itenas.uas.pojo.Komik;
import org.itenas.uas.pojo.Member;
import org.itenas.uas.pojo.Sewa;
import org.itenas.uas.service.MemberService;
import org.itenas.uas.service.SewaService;
import org.itenas.uas.service.TransaksiService;
import org.itenas.uas.serviceimpl.BukuServiceImpl;
import org.itenas.uas.serviceimpl.KomikServiceImpl;
import org.itenas.uas.serviceimpl.MemberServiceImpl;
import org.itenas.uas.serviceimpl.SewaServiceImpl;
import org.itenas.uas.serviceimpl.TransaksiServiceImpl;

/**
 *
 * @author Kelompok 1
 */
public class SewaKomik extends javax.swing.JFrame {

    KomikServiceImpl komikService;
    Komik komik;
    Sewa sewa;
    Member member;
    SewaService sewaService;
    MemberService memberService;
    TransaksiService transaksiService;
    MessageForm messageForm;
    static List<Sewa> listSewa = new ArrayList<>();
    String idKomik;
    boolean cek = false;
    double totalHarga = 0;
    
    public SewaKomik() {
        initComponents();
        this.setLocationRelativeTo(null);
        comboBoxModel();
        btn_tambah.setEnabled(cek);
        lbl_hidden.setVisible(cek);
    }
    
    private void emptyField(){
        cmb_idKomik.setSelectedIndex(0);
        txt_judul.setText("");
        txt_pengarang.setText("");
        txt_penerbit.setText("");
        txt_tahunTerbit.setText("");
        txt_harga.setText("");
        txt_status.setText("");
        txt_volume.setText("");
        chooser_tglSewa.setCalendar(null);
        cek = false;
        btn_tambah.setEnabled(cek);
   }

    private void comboBoxModel(){
        komikService = new KomikServiceImpl();
        List<Komik> listKomik = new ArrayList<>();
        listKomik = komikService.findAll();
        String[] objectKomik = new String[listKomik.size()+1];
        
        //Index pertama agar pilihan
        objectKomik[0] = "Pilih ID Komik";
        
        int counter = 1;
        
        for(Komik komik : listKomik){
            objectKomik[counter] = komik.getId();
            counter++;
        }
        
        DefaultComboBoxModel<String> komikModel = new DefaultComboBoxModel<>(objectKomik);
        cmb_idKomik.setModel(komikModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_idMember = new javax.swing.JTextField();
        cmb_idKomik = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        txt_tahunTerbit = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbl_totalHarga = new javax.swing.JLabel();
        btn_checkout = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        chooser_tglSewa = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        lbl_hidden = new javax.swing.JLabel();
        txt_volume = new javax.swing.JTextField();
        lbl_status1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        judul.setBackground(new java.awt.Color(245, 172, 44));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEWA KOMIK");

        javax.swing.GroupLayout judulLayout = new javax.swing.GroupLayout(judul);
        judul.setLayout(judulLayout);
        judulLayout.setHorizontalGroup(
            judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judulLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
        );
        judulLayout.setVerticalGroup(
            judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 172, 44));
        jLabel2.setText(": Buku apa yang ingin Anda pesan kali ini?");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 172, 44));
        jLabel4.setText("Tekan \"Tambah\" untuk menambahkan buku");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 172, 44));
        jLabel5.setText("ID Komik          :");

        txt_idMember.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));
        txt_idMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idMemberActionPerformed(evt);
            }
        });

        cmb_idKomik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_idKomikActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 172, 44));
        jLabel6.setText("Judul                 :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 172, 44));
        jLabel7.setText("Pengarang         :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 172, 44));
        jLabel8.setText("Penerbit             :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 172, 44));
        jLabel9.setText("Tahun Terbit      :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 172, 44));
        jLabel10.setText("Harga                :");

        lbl_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(245, 172, 44));
        lbl_status.setText("Status                :");

        txt_judul.setEditable(false);
        txt_judul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));

        txt_pengarang.setEditable(false);
        txt_pengarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));

        txt_penerbit.setEditable(false);
        txt_penerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));

        txt_tahunTerbit.setEditable(false);
        txt_tahunTerbit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));
        txt_tahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tahunTerbitActionPerformed(evt);
            }
        });

        txt_harga.setEditable(false);
        txt_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));

        txt_status.setEditable(false);
        txt_status.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));
        txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusActionPerformed(evt);
            }
        });

        btn_tambah.setBackground(new java.awt.Color(245, 172, 44));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });

        btn_bersihkan.setBackground(new java.awt.Color(245, 172, 44));
        btn_bersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btn_bersihkan.setText("BERSIHKAN");
        btn_bersihkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bersihkanMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("TOTAL PEMBELIAN:");

        lbl_totalHarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_totalHarga.setForeground(new java.awt.Color(102, 102, 102));
        lbl_totalHarga.setText("Rp. ");

        btn_checkout.setBackground(new java.awt.Color(51, 255, 51));
        btn_checkout.setForeground(new java.awt.Color(255, 255, 255));
        btn_checkout.setText("CHECKOUT");
        btn_checkout.setEnabled(false);
        btn_checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_checkoutMouseClicked(evt);
            }
        });
        btn_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkoutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(245, 172, 44));
        jLabel13.setText("Tanggal Pengembalian :");

        chooser_tglSewa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(245, 172, 44));
        jLabel14.setText("ID Member       :");

        lbl_hidden.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hidden.setText("ID Member tidak ada");

        txt_volume.setEditable(false);
        txt_volume.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(245, 172, 44)));
        txt_volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_volumeActionPerformed(evt);
            }
        });

        lbl_status1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_status1.setForeground(new java.awt.Color(245, 172, 44));
        lbl_status1.setText("Volume              :");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_totalHarga))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(btn_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(btn_bersihkan))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooser_tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(lbl_status)
                                    .addComponent(lbl_status1))
                                .addGap(28, 28, 28)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_idKomik, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(txt_idMember, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_hidden))
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(txt_harga, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_penerbit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_pengarang, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_judul, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_volume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_checkout)
                .addGap(35, 35, 35))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_idMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hidden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_idKomik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_status1))
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chooser_tglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_bersihkan))
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_totalHarga))
                .addGap(3, 3, 3)
                .addComponent(btn_checkout)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahunTerbitActionPerformed

    private void txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusActionPerformed

    private void cmb_idKomikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_idKomikActionPerformed
    double harga;
    komikService = new KomikServiceImpl();
    komik = new Komik();
    idKomik = cmb_idKomik.getSelectedItem().toString();
    
    komik = komikService.findById(idKomik);
    if (komik != null) {
        txt_judul.setText(komik.getJudul());
        txt_pengarang.setText(komik.getPengarang());
        txt_penerbit.setText(komik.getPenerbit());
        txt_tahunTerbit.setText(komik.getTahunTerbit());
        harga = komik.getHarga();
        txt_harga.setText("Rp. "+harga);
        txt_status.setText(komik.getStatus());
        txt_volume.setText(komik.getVolume());

        if(komik.getStatus().equals("Tersedia")){
            txt_status.setForeground(Color.GREEN);
            cek = true;
            btn_tambah.setEnabled(cek);
        }
        else if(komik.getStatus().equals("Tidak Tersedia")){
            txt_status.setForeground(Color.red);
            cek = false;
            btn_tambah.setEnabled(cek);
        }
    } else {
        emptyField();
    }
    }//GEN-LAST:event_cmb_idKomikActionPerformed

    private void btn_bersihkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bersihkanMouseClicked
        emptyField();
    }//GEN-LAST:event_btn_bersihkanMouseClicked

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
String tglSewa, tglKembali, idMember;
double harga = 0;
double biayaPerHari = 2000; 

Date date = chooser_tglSewa.getDate();

if (date == null) {
    JOptionPane.showMessageDialog(null, "Silahkan masukkan tanggal terlebih dahulu.", "Tanggal Belum dipilih!", JOptionPane.WARNING_MESSAGE);
    return;
}

LocalDate currentDate = LocalDate.now();
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
tglKembali = formatter.format(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
tglSewa = formatter.format(currentDate);
idKomik = cmb_idKomik.getSelectedItem().toString();
idMember = txt_idMember.getText();

String hargaText = txt_harga.getText();
String numericPart = hargaText.replace("Rp.", "").replace(",", "");
harga = Double.parseDouble(numericPart);

sewa = new Sewa();
sewa.setTglSewa(tglSewa);
sewa.setTglKembali(tglKembali);

java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
java.util.Date datePinjam;
double totalBiaya = 0;  //

try {
    datePinjam = sdf.parse(tglSewa);
    java.util.Date datePengembalian = sdf.parse(tglKembali);
    long selisihHari = (datePengembalian.getTime() - datePinjam.getTime()) / (24 * 60 * 60 * 1000);

    if (selisihHari < 0) {
        JOptionPane.showMessageDialog(this, "Tanggal pengembalian harus setelah tanggal pinjam.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    totalBiaya = biayaPerHari * selisihHari;
    sewa.setTotalHarga(totalBiaya);

} catch (ParseException e) {
    e.printStackTrace();
}

sewa.setStatus("Belum dibayar");
sewa.setDenda(0);

komik = new Komik();
komik.setId(idKomik);
sewa.setKomik(komik);

member = new Member();
member.setId(idMember);
sewa.setMember(member);

listSewa.add(sewa);

btn_checkout.setEnabled(true);
totalHarga += totalBiaya;
lbl_totalHarga.setText("Rp. " + totalHarga);

messageForm = new MessageForm();
messageForm.gantiText("PESAN", "Data Komik berhasil ditambahkan.", "Lanjutkan");
messageForm.setVisible(true);
emptyField();

    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_checkoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkoutMouseClicked
        int counter = 0;
        sewaService = new SewaServiceImpl();
        transaksiService = new TransaksiServiceImpl();
        for(Sewa sewa : listSewa){
            sewaService.create(sewa);
            transaksiService.updateStatusPeminjamanKomik(sewa);
            counter++;
        }
        
        messageForm = new MessageForm();
        messageForm.gantiText("TRANSAKSI DIBUAT", "Silahkan pergi ke kasir untuk membayar.", "Lanjutkan");
        messageForm.setVisible(true);
    }//GEN-LAST:event_btn_checkoutMouseClicked

    private void txt_idMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idMemberActionPerformed
        String idMember = txt_idMember.getText();
        member = new Member();
        memberService = new MemberServiceImpl();
        
        member = memberService.findById(idMember);
        
        if(member == null){
            lbl_hidden.setVisible(true);
        } else{
            lbl_hidden.setVisible(false);
        }
        
    }//GEN-LAST:event_txt_idMemberActionPerformed

    private void txt_volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_volumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_volumeActionPerformed

    private void btn_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaKomik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaKomik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_tambah;
    private com.toedter.calendar.JDateChooser chooser_tglSewa;
    private javax.swing.JComboBox<String> cmb_idKomik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel judul;
    private javax.swing.JLabel lbl_hidden;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_status1;
    private javax.swing.JLabel lbl_totalHarga;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_idMember;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_tahunTerbit;
    private javax.swing.JTextField txt_volume;
    // End of variables declaration//GEN-END:variables
}
